import Foundation

/// A non-obvious connection discovered across multiple domains of user activity.
/// Generated by SynthesisEngine when it detects that data from 2+ sources relates
/// in a way the user is unlikely to have noticed.
struct SynthesisInsight: Codable, Identifiable, Sendable {
    let id: UUID
    let headline: String            // "Your quantum computing research connects to Sarah's Thursday presentation"
    let explanation: String         // 2-3 sentence explanation of the connection
    let domains: [String]           // ["Safari browsing", "Calendar", "Downloads"]
    let surpriseScore: Double       // 0.0-1.0 — LLM's self-assessed novelty (reject < 0.6)
    let actionSuggestion: String?   // Optional: "Want me to pull the PDF into your presentation outline?"
    let createdAt: Date
    let sourceData: SourceSnapshot

    struct SourceSnapshot: Codable, Sendable {
        let thoughtSummaries: [String]
        let relevantMemories: [String]
        let activeGoals: [String]
        let recentFiles: [String]
    }
}
