import Foundation
import Cocoa

enum SyncStatus: Equatable {
    case idle
    case synced(Date)
    case savedLocally(Date)
    case error(String)
}

class HandoffService: ObservableObject {
    static let shared = HandoffService()

    @Published var lastSyncStatus: SyncStatus = .idle

    private var iCloudAvailable: Bool = false
    private let iCloudHandoffDir: URL?
    private let localHandoffDir: URL
    private let queue = DispatchQueue(label: "com.executer.handoff", qos: .utility)
    private let maxResponseLength = 50_000
    private let minResponseLength = 200
    private let pruneAfterDays = 30

    /// Cached formatters — DateFormatter creation is expensive, reuse across calls
    private let filenameDateFormatter: DateFormatter = {
        let f = DateFormatter()
        f.dateFormat = "yyyy-MM-dd_HH-mm-ss"
        return f
    }()
    private let displayDateFormatter: DateFormatter = {
        let f = DateFormatter()
        f.dateFormat = "MMMM d, yyyy 'at' h:mm a"
        return f
    }()
    private let isoFormatter = ISO8601DateFormatter()

    private init() {
        // Local fallback path
        let appSupport = FileManager.default.urls(for: .applicationSupportDirectory, in: .userDomainMask).first!
        localHandoffDir = appSupport.appendingPathComponent("Executer/Handoffs", isDirectory: true)
        try? FileManager.default.createDirectory(at: localHandoffDir, withIntermediateDirectories: true)

        // iCloud path
        let iCloudBase = FileManager.default.homeDirectoryForCurrentUser
            .appendingPathComponent("Library/Mobile Documents/com~apple~CloudDocs", isDirectory: true)

        if FileManager.default.fileExists(atPath: iCloudBase.path) {
            let dir = iCloudBase.appendingPathComponent("Executer/Handoffs", isDirectory: true)
            try? FileManager.default.createDirectory(at: dir, withIntermediateDirectories: true)
            iCloudHandoffDir = dir
            iCloudAvailable = true
            print("[Handoff] iCloud Drive available")
        } else {
            iCloudHandoffDir = nil
            iCloudAvailable = false
            print("[Handoff] iCloud Drive not available, using local storage")
        }

        // Recheck iCloud when app becomes active
        NotificationCenter.default.addObserver(
            forName: NSApplication.didBecomeActiveNotification,
            object: nil,
            queue: .main
        ) { [weak self] _ in
            self?.recheckICloud()
        }

        // Initial prune
        queue.async { [weak self] in
            self?.pruneOldHandoffs()
        }
    }

    // MARK: - Save

    func saveHandoff(command: String, response: String, appContext: String? = nil) {
        // Only save substantive outputs
        guard response.count >= minResponseLength else { return }
        guard !response.hasPrefix("Error:") else { return }

        queue.async { [weak self] in
            guard let self = self else { return }

            let truncated = String(response.prefix(self.maxResponseLength))
            let now = Date()

            // Generate filename
            let dateStr = self.filenameDateFormatter.string(from: now)
            let slug = self.slugify(command)
            let filename = "\(dateStr)_\(slug).md"

            // Generate markdown
            let displayDate = self.displayDateFormatter.string(from: now)

            var markdown = "# \(command)\n\n"
            markdown += "*Generated by Executer on \(displayDate)*\n"
            if let ctx = appContext {
                markdown += "*Context: \(ctx)*\n"
            }
            markdown += "\n---\n\n"
            markdown += truncated

            // Write to the appropriate directory
            let targetDir = self.iCloudAvailable ? (self.iCloudHandoffDir ?? self.localHandoffDir) : self.localHandoffDir
            let fileURL = targetDir.appendingPathComponent(filename)

            do {
                try markdown.write(to: fileURL, atomically: true, encoding: .utf8)

                // Update latest.json
                let summary = String(truncated.prefix(200))
                    .replacingOccurrences(of: "\n", with: " ")
                    .trimmingCharacters(in: .whitespacesAndNewlines)

                let latest: [String: Any] = [
                    "topic": command,
                    "timestamp": self.isoFormatter.string(from: now),
                    "filename": filename,
                    "summary": summary,
                    "wordCount": truncated.split(separator: " ").count
                ]

                let latestData = try JSONSerialization.data(withJSONObject: latest, options: [.prettyPrinted, .sortedKeys])
                let latestURL = targetDir.appendingPathComponent("latest.json")
                try latestData.write(to: latestURL, options: .atomic)

                let status: SyncStatus = self.iCloudAvailable ? .synced(now) : .savedLocally(now)
                DispatchQueue.main.async {
                    self.lastSyncStatus = status
                }

                print("[Handoff] Saved: \(filename) (\(self.iCloudAvailable ? "iCloud" : "local"))")
            } catch {
                print("[Handoff] Save failed: \(error)")
                DispatchQueue.main.async {
                    self.lastSyncStatus = .error(error.localizedDescription)
                }
            }
        }
    }

    // MARK: - Prune

    private func pruneOldHandoffs() {
        let dirs = [localHandoffDir, iCloudHandoffDir].compactMap { $0 }
        let cutoff = Date().addingTimeInterval(-Double(pruneAfterDays) * 86400)

        for dir in dirs {
            guard let files = try? FileManager.default.contentsOfDirectory(
                at: dir,
                includingPropertiesForKeys: [.contentModificationDateKey]
            ) else { continue }

            for file in files {
                guard file.pathExtension == "md" else { continue }
                guard let attrs = try? file.resourceValues(forKeys: [.contentModificationDateKey]),
                      let modified = attrs.contentModificationDate,
                      modified < cutoff else { continue }

                try? FileManager.default.removeItem(at: file)
                print("[Handoff] Pruned old file: \(file.lastPathComponent)")
            }
        }
    }

    // MARK: - Helpers

    private func recheckICloud() {
        let iCloudBase = FileManager.default.homeDirectoryForCurrentUser
            .appendingPathComponent("Library/Mobile Documents/com~apple~CloudDocs", isDirectory: true)

        let wasAvailable = iCloudAvailable
        iCloudAvailable = FileManager.default.fileExists(atPath: iCloudBase.path)

        if iCloudAvailable && !wasAvailable {
            // iCloud became available — create directory
            if let dir = iCloudHandoffDir {
                try? FileManager.default.createDirectory(at: dir, withIntermediateDirectories: true)
            }
            print("[Handoff] iCloud Drive became available")
        } else if !iCloudAvailable && wasAvailable {
            print("[Handoff] iCloud Drive became unavailable")
        }
    }

    private func slugify(_ text: String) -> String {
        let words = text.lowercased()
            .components(separatedBy: CharacterSet.alphanumerics.inverted)
            .filter { !$0.isEmpty }
            .prefix(5)
        let slug = words.joined(separator: "-")
        return slug.isEmpty ? "output" : String(slug.prefix(50))
    }

    deinit {
        NotificationCenter.default.removeObserver(self)
    }
}
